[package]
name = "rustify"
version = "0.1.0"
authors = ["Petr Hodina <hodinapetr46@gmail.com>"]
build = "build.rs"

[build-dependencies]
bindgen = "0.31.3"
cc = "1"

[dependencies]
error-chain = "0.11"
clap = "2.27.1"